# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andy Xiong's blog
email: thinman918@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Andy Xiong, engaged in web developing from 2012. I worked for Tianjin Shenzhou Shanglong
  technical co.,ltd, 
  dealing with the project of Restaurant Management System, the main libs are bootstrap and jquery.
  2015 ~ 2016: I worked for Aircos inc dealing with the project of Logistics Management System, the main libs
  are  sui and zepto.
  2016 ~ now: I work for Gfresh inc dealing with Gstore system. React is my favorite js lib 
  fitting in with Redux, Axios and Webpack.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.4soho.cn" # the base hostname & protocol for your site
twitter_username: 
github_username:  xwenc

# Build settings
markdown: kramdown
theme: minima
